language: node_js
node_js:
    - 6
cache:
    directories:
        - node_modules
script:
    - npm test -- --coverage
    - npm run build
    - zip -r build.zip build/

after_success:
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deploy:
  provider: releases
  api_key:
    secure: oqPpnTXbwEMU5Ut5/7qDVvwouoG6+9YwZMtyJtyuz5Xq6pG97TCumYBbQonTFowJiG4PaojgsXZ2bp3rN7kzdDCKaFFwPH350KJaEVfYUmDQmwSzH+NIOS/wE5Ai1L5npMktGW8eQeBDPRgjwOkBEA228FKX5i4TdM+JV8HYkz5gQXoJRRS0eDi9Ot1KtlavohgKK2S/b+aaNBa8eOqEtfE7cSXsk4yvqYbbWILHIVmRwmTkLRBpufD5+I+5o4H15xel07OE4c0mK9HRwsVQAxqtF1G/mBu4f90f0fPusVzlejUKMe3KtQUjQyW//jtMUEdm12YiL4jqRjaDK+X6lmGfYVTMqS39ny+tCZ/m+Q/cRT/n57bf0U08UwNtGMxCtJnRm64zkTtfGP3C2KJZWx0t+gxGc77qvm3G7Njjlg1NInl05ipIUWuUxm2m+5Qj9TcJwWteehzMA9XhXlpnEN/9GZWrQ4V8+zzbmQCpqzoL4djLIb05AnzFiLIiREJQTFVrzVDmdeBUBNmTQQnh7BALIdm8ih/pqij6/XgIYmDD2yhomSnOFrjXD0UIynmwuxjCI4Ki7rY0sSmm+9inmqYV1XlsRxbG9sMWmEm5bK8SyVBWoXkWF1l9/fDJQj9E2goTbq6mXwGCAhPSNtVqnQSuXtPAQwwFffYukNEdRPU=
  file:
      - build.zip
  skip_cleanup: true
  on:
    branch: master
